### ISSUE TITLE
unable to run - no errors

### ISSUE THREAD

**Issue by cekvenich** [crisward/riot-flipcard#2]
Hi, I just copied your code.
Here:  http://murder.site44.com/flip.html

It does not run and no hints as to how I get it to run.
Help please? :-)

**Comment by crisward** [comment]
It works fine for me. Which web browser are you using? You know this doesn't yet work with internet explorer 11?

**Comment by cekvenich** [comment]
<img width="626" alt="screen shot 2016-11-05 at 7 04 38 pm" src="https://cloud.githubusercontent.com/assets/22248870/20034846/c9811444-a38a-11e6-945c-11bb0261dc3d.png">

Chrome and FF in OSX - both latest. Attached is screen shot.
